### ISSUE TITLE
Frequencies.ino errors

### ISSUE THREAD

**Issue by bncdemo** [sheaivey/ESP32-AudioInI2S#1]
It is not possible to compile frequencies.ino 

The error message:

In file included from ~\Documents\Arduino\Frequencies\Frequencies.ino:18:
~\Documents\Arduino\libraries\AudioInI2S/AudioAnalysis.h:143:3: error: 'ArduinoFFT' does not name a type; did you mean 'arduinoFFT'?
   ArduinoFFT<float> *_FFT = nullptr;
   ^~~~~~~~~~
   arduinoFFT
~\Documents\Arduino\libraries\AudioInI2S/AudioAnalysis.h: In member function 'void AudioAnalysis::computeFFT(int32_t*, int, int)':
~\Documents\Arduino\libraries\AudioInI2S/AudioAnalysis.h:158:7: error: '_FFT' was not declared in this scope
   if (_FFT == nullptr || _sampleSize != sampleSize || _sampleRate != sampleRate)
       ^~~~
~\Documents\Arduino\libraries\AudioInI2S/AudioAnalysis.h:162:16: error: 'ArduinoFFT' does not name a type; did you mean 'arduinoFFT'?
     _FFT = new ArduinoFFT<float>(_real, _imag, _sampleSize, _sampleRate, _weighingFactors);
                ^~~~~~~~~~
                arduinoFFT
~\Documents\Arduino\libraries\AudioInI2S/AudioAnalysis.h:162:27: error: expected primary-expression before 'float'
     _FFT = new ArduinoFFT<float>(_real, _imag, _sampleSize, _sampleRate, _weighingFactors);
                           ^~~~~
~\Documents\Arduino\libraries\AudioInI2S/AudioAnalysis.h:172:3: error: '_FFT' was not declared in this scope
   _FFT->dcRemoval();
   ^~~~

exit status 1

Compilation error: exit status 1

**Comment by sheaivey** [comment]
Could you provide more information? It compiles just fine for me on Arduino IDE v2.1.1-nightly-20230502

**Comment by bncdemo** [comment]
I had to remove the aurdinoFTT library, then download and manually install the arduinoFFT-develop source.
With that everything is ok.
Is there a way to contact you? /related to this project but not to this topic/

**Comment by sheaivey** [comment]
Oh right! The module is using the ArduinoFFT develop version which is faster and has a lot more features. I believe that is called out in the readme but it could probably be more prominent. [Known Issues](https://github.com/sheaivey/ESP32-AudioInI2S#known-issues)

I wish they would just publish the develop branch under a new project.
