### ISSUE TITLE
not working with ESP32 v3.03

### ISSUE THREAD

**Issue by Sascha8** [sheaivey/ESP32-AudioInI2S#5]
HI,
`mic.read(samples)` 
returns always 0 with the latest ESP32 lib. Please fix!

Thx!

**Comment by Sascha8** [comment]
looking deeper in this I found  using `I2S_CHANNEL_FMT_ONLY_LEFT` at the constructor get it back to work fine :)

`AudioInI2S mic(SCK_PIN, WS_PIN, SD_PIN, -1, I2S_CHANNEL_FMT_ONLY_LEFT); `

**Comment by sheaivey** [comment]
Glad you were able to find that on your own. Not all MEMS microphones default to sending to the `I2S_CHANNEL_FMT_ONLY_RIGHT` channel, I just picked the default that worked with the ones I have. 

I'll update the AudioInI2S Readme for some trouble shooting help.

Thanks

**Comment by sheaivey** [comment]
Added some trouble shooting notes here...
https://github.com/sheaivey/ESP32-AudioInI2S/commit/c5e1e339e38535b951412e220c5e0eda5a5cb795
